### ISSUE TITLE
大佬，找不到yibu包，程序报错了，要怎么解决啊

### ISSUE THREAD

**Issue by foreverhell** [fristyy/-#1]

**Comment by fristyy** [comment]
具体什么情况？测试是正常的，是没有安装好依赖包吗？下载后解压到一个目录中，在这个目录中包含requirments.txt，执行说明里的安装命令，就会安装好requirments.txt中列出的模块，再在目录中执行启动命令就行了

**Comment by foreverhell** [comment]
> 具体什么情况？测试是正常的，是没有安装好依赖包吗？下载后解压到一个目录中，在这个目录中包含requirments.txt，执行说明里的安装命令，就会安装好requirments.txt中列出的模块，再在目录中执行启动命令就行了
解压后pip install -r requirements.txt，下面是安装结果
![image](https://github.com/user-attachments/assets/d8e8448c-d2ae-42f7-9077-94ed2c396613)
下面是运行结果
![image](https://github.com/user-attachments/assets/9d6c3c0e-1bc1-40b8-a024-5ccebda73bf1)

**Comment by fristyy** [comment]
是使用3.10版本的Python吗？我试一下可能必须使用3.10版，然后如果导入没问题，报numpy错误的话，注意numpy包要降级到1.26版本

**Comment by fristyy** [comment]
![image](https://github.com/user-attachments/assets/1d339e25-9bc8-4de7-b096-6ed2eb7e7744)
试过了可能其它版本的python不行，因为yibu模块在3.10下做的编译，你试试看，我重新搭了环境3.10.6这个版本没问题，另外把requirements.txt中的numpy版本改成1.26.0或1.26就可以了。

1,装3.10.6版的Python,
2,启动时如果遇到numpy问题
   pip uninstall numpy         先卸载
   pip install numpy==1.26 再安装指定的numpy

**Comment by foreverhell** [comment]
> ![image](https://private-user-images.githubusercontent.com/31688915/380367102-1d339e25-9bc8-4de7-b096-6ed2eb7e7744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzQ2NDAsIm5iZiI6MTczMDAzNDM0MCwicGF0aCI6Ii8zMTY4ODkxNS8zODAzNjcxMDItMWQzMzllMjUtOWJjOC00ZGU3LWIwOTYtNmVkMmViN2U3NzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDEzMDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4OGU3N2NlZTU0NTJhZjJlNTU4ZTVjOWQ1Zjk4ZmFlNjg3OGU4NGQ5OWZmNTc5MzAyNjU3NGU1ODY5ZGQ2M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.npdGa6cBCEJZDGTsbRwCpl3xbSsJdcH3P2-sSKRhBLs) 试过了可能其它版本的python不行，因为yibu模块在3.10下做的编译，你试试看，我重新搭了环境3.10.6这个版本没问题，另外把requirements.txt中的numpy版本改成1.26.0或1.26就可以了。
> 
> 1,装3.10.6版的Python, 2,启动时如果遇到numpy问题 pip uninstall numpy 先卸载 pip install numpy==1.26 再安装指定的numpy

我可能知道为什么了，
[yibu.cp310-win_amd64.pyd](https://github.com/fristyy/ChangeOFBookTool/blob/main/yibu.cp310-win_amd64.pyd)
yibu是在windows操作系统上编译的C代码，应该只能用windows操作系统，我需要试一下

**Comment by fristyy** [comment]
用我新上传dist文件夹里的内容替换掉yibu.cp310-win_amd64.pyd就应该可以不受系统限制了

**Comment by foreverhell** [comment]
> ![image](https://private-user-images.githubusercontent.com/31688915/380367102-1d339e25-9bc8-4de7-b096-6ed2eb7e7744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODUzNTAsIm5iZiI6MTczMDA4NTA1MCwicGF0aCI6Ii8zMTY4ODkxNS8zODAzNjcxMDItMWQzMzllMjUtOWJjOC00ZGU3LWIwOTYtNmVkMmViN2U3NzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAzMTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMGM5YmE0ZjZmMTM4NWUwYjBhOTZlODhlMmJlOWNlZTI1M2NlZGI3NjNjMGI4YzIxZmM1NTQ3ZTZmYTk1MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pN3hQPuZx4qQYHh2qfqttUg7qdRkBxM8SXy1Gb6PDUw) 试过了可能其它版本的python不行，因为yibu模块在3.10下做的编译，你试试看，我重新搭了环境3.10.6这个版本没问题，另外把requirements.txt中的numpy版本改成1.26.0或1.26就可以了。
> 
> 1,装3.10.6版的Python, 2,启动时如果遇到numpy问题 pip uninstall numpy 先卸载 pip install numpy==1.26 再安装指定的numpy

搞定了！
系统windows，python3.10，numpy1.26.
感谢大佬！
